import { registerAuthInfrastructure } from '@/modules/auth/infrastructure/register';
import { registerAnalysisInfrastructure } from '@/modules/analysis/infrastructure/register';
import { registerApiTrackerInfrastructure } from '@/modules/api-tracker/infrastructure/register';
import { registerCanvasInfrastructure } from '@/modules/canvas/infrastructure/register';
import { registerChatInfrastructure } from '@/modules/chat/infrastructure/register';
import { registerClusterInfrastructure } from '@/modules/clusters/infrastructure/register';
import { registerContainerInfrastructure } from '@/modules/container/infrastructure/register';
import { registerDailyActivityInfrastructure } from '@/modules/daily-activity/infrastructure/register';
import { registerJobsInfrastructure } from '@/modules/jobs/infrastructure/register';
import { registerNotificationInfrastructure } from '@/modules/notification/infrastructure/register';
import { registerPluginInfrastructure } from '@/modules/plugins/infrastructure/register';
import { registerRasterInfrastructure } from '@/modules/raster/infrastructure/register';
import { registerSearchInfrastructure } from '@/modules/search/infrastructure/register';
import { registerSimulationCellInfrastructure } from '@/modules/simulation-cell/infrastructure/register';
import { registerSSHInfrastructure } from '@/modules/ssh/infrastructure/register';
import { registerTeamInfrastructure } from '@/modules/team/infrastructure/register';
import { registerTeamInvitationInfrastructure } from '@/modules/team-invitation/infrastructure/register';
import { registerTeamRoleInfrastructure } from '@/modules/team-role/infrastructure/register';
import { registerTrajectoryInfrastructure } from '@/modules/trajectory/infrastructure/register';

export const registerModuleInfrastructure = (): void => {
    registerAuthInfrastructure();
    registerAnalysisInfrastructure();
    registerApiTrackerInfrastructure();
    registerCanvasInfrastructure();
    registerChatInfrastructure();
    registerClusterInfrastructure();
    registerContainerInfrastructure();
    registerDailyActivityInfrastructure();
    registerJobsInfrastructure();
    registerNotificationInfrastructure();
    registerPluginInfrastructure();
    registerRasterInfrastructure();
    registerSearchInfrastructure();
    registerSimulationCellInfrastructure();
    registerSSHInfrastructure();
    registerTeamInfrastructure();
    registerTeamInvitationInfrastructure();
    registerTeamRoleInfrastructure();
    registerTrajectoryInfrastructure();
};
