export const ErrorCodes = {
    // Docker / Container
    CONTAINER_CREATION_FAILED: 'CONTAINER_CREATION_FAILED',
    CONTAINER_START_FAILED: 'CONTAINER_START_FAILED',
    CONTAINER_STOP_FAILED: 'CONTAINER_STOP_FAILED',
    CONTAINER_DELETION_FAILED: 'CONTAINER_DELETION_FAILED',
    CONTAINER_STATS_FAILED: 'CONTAINER_STATS_FAILED',
    CONTAINER_FILE_READ_FAILED: 'CONTAINER_FILE_READ_FAILED',
    CONTAINER_EXEC_FAILED: 'CONTAINER_EXEC_FAILED',
    CONTAINER_NOT_FOUND: 'CONTAINER_NOT_FOUND',

    // Legacy mapping or specific new ones can be added here
    DOCKER_IMAGE_PULL_FAILED: 'DOCKER_IMAGE_PULL_FAILED',
    DOCKER_CONNECT_ERROR: 'DOCKER_CONNECT_ERROR',
};
