export const ValidationCodes = {
    CONTAINER_NAME_REQUIRED: 'CONTAINER_NAME_REQUIRED',
    CONTAINER_IMAGE_REQUIRED: 'CONTAINER_IMAGE_REQUIRED',
    CONTAINER_ID_REQUIRED: 'CONTAINER_ID_REQUIRED',
    CONTAINER_CREATED_BY_REQUIRED: 'CONTAINER_CREATED_BY_REQUIRED',
};
